/gate/geometry/setMaterialDatabase ../GateMaterials.db

/gate/world/geometry/setXLength 1000. cm
/gate/world/geometry/setYLength 1000. cm
/gate/world/geometry/setZLength 300. cm

/gate/world/daughters/name scanner
/gate/world/daughters/insert box
/gate/scanner/geometry/setXLength 900. cm
/gate/scanner/geometry/setYLength 900. cm
/gate/scanner/geometry/setZLength 250. cm
/gate/scanner/setMaterial Vacuum
/gate/scanner/vis/forceWireframe

/gate/scanner/daughters/name waterbox
/gate/scanner/daughters/insert box
/gate/waterbox/geometry/setXLength 800. cm
/gate/waterbox/geometry/setYLength 800. cm
/gate/waterbox/geometry/setZLength 100. cm
/gate/waterbox/placement/setTranslation 0. 0. 50. cm
/gate/waterbox/setMaterial Water
/gate/waterbox/vis/forceWireframe

/gate/waterbox/attachCrystalSD

#===============#
# Physics	#
#===============#

/gate/geometry/setIonisationPotential Water 75 eV
/gate/physics/addPhysicsList QGSP_BIC

/gate/run/initialize

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource uniformBeam gps
/gate/source/uniformBeam/gps/particle proton
/gate/source/uniformBeam/gps/ene/type Gauss
/gate/source/uniformBeam/gps/ene/mono {energy} MeV
/gate/source/uniformBeam/gps/ene/sigma {sigma} MeV
/gate/source/uniformBeam/gps/type Plane
/gate/source/uniformBeam/gps/shape Square
/gate/source/uniformBeam/gps/direction 0 0 1
/gate/source/uniformBeam/gps/halfx 0. mm
/gate/source/uniformBeam/gps/halfy 0. mm
/gate/source/uniformBeam/gps/centre 0. 0. -0.1 mm # -20 cm for scintillator

/gate/output/root/enable
#/gate/output/root/setFileName /scratch/focal/focalCode/Scripts/MCCodeComparison/Data/GATE/Aluminium/aluminium_{energy}MeV
#/gate/output/root/setFileName /home/local1/focal/focalCode/Scripts/MCCodeComparison/Data/GATE/Aluminium/aluminium_{energy}MeV
/gate/output/root/setFileName /scratch/focal/focalCode/Scripts/MCCodeComparison/Data/GATE/Water/water_qgspbic_{energy}MeV

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries {npart}
/gate/application/start
