/gate/geometry/setMaterialDatabase GateMaterials.db

/gate/world/geometry/setXLength 1000. cm
/gate/world/geometry/setYLength 1000. cm
/gate/world/geometry/setZLength 1000. cm

/gate/world/daughters/name scanner
/gate/world/daughters/insert box
/gate/scanner/geometry/setXLength 500. cm
/gate/scanner/geometry/setYLength 500. cm
/gate/scanner/geometry/setZLength 500. cm
/gate/scanner/placement/setTranslation 0 0 0. cm
/gate/scanner/setMaterial Vacuum
/gate/scanner/vis/forceWireframe

/gate/scanner/daughters/name fronttracker
/gate/scanner/daughters/insert box
/gate/fronttracker/geometry/setXLength 100. cm
/gate/fronttracker/geometry/setYLength 100. cm
/gate/fronttracker/geometry/setZLength 0.001 mm
/gate/fronttracker/placement/setTranslation 0 0 -{ztracker} mm # -dz/2 - 15
/gate/fronttracker/setMaterial Vacuum

/gate/fronttracker/repeaters/insert linear
/gate/fronttracker/linear/autoCenter true
/gate/fronttracker/linear/setRepeatNumber 2
/gate/fronttracker/linear/setRepeatVector 0 0 10. mm

/gate/scanner/daughters/name backtracker
/gate/scanner/daughters/insert box
/gate/backtracker/geometry/setXLength 100. cm
/gate/backtracker/geometry/setYLength 100. cm
/gate/backtracker/geometry/setZLength 0.001 mm
/gate/backtracker/placement/setTranslation 0 0 {ztracker} mm # dz/2 + 15
/gate/backtracker/setMaterial Vacuum

/gate/backtracker/repeaters/insert linear
/gate/backtracker/linear/autoCenter true
/gate/backtracker/linear/setRepeatNumber 2
/gate/backtracker/linear/setRepeatVector 0 0 10. mm

/gate/scanner/daughters/name phantom
/gate/scanner/daughters/insert box
/gate/phantom/geometry/setXLength 100. cm
/gate/phantom/geometry/setYLength 100. cm
/gate/phantom/geometry/setZLength {dz} mm
/gate/phantom/placement/setTranslation 0 0 0 mm
/gate/phantom/setMaterial {material}
/gate/phantom/vis/forceWireframe

/gate/scanner/daughters/name calorimeter
/gate/scanner/daughters/insert box
/gate/calorimeter/geometry/setXLength 200. cm
/gate/calorimeter/geometry/setYLength 200. cm
/gate/calorimeter/geometry/setZLength 200. cm
/gate/calorimeter/placement/setTranslation 0 0 {zcalorimeter} mm # dz/2 + 30
/gate/calorimeter/setMaterial Tungsten

/gate/phantom/attachCrystalSD
/gate/fronttracker/attachCrystalSD
/gate/backtracker/attachCrystalSD
/gate/calorimeter/attachCrystalSD

/gate/physics/addPhysicsList QGSP_BIC_EMZ
/gate/geometry/setIonisationPotential Water 78 eV

/gate/physics/SetMaxStepSizeInRegion phantom 2 mm
/gate/physics/SetMinKineticEnergyInRegion calorimeter 300 MeV
/gate/physics/ActivateSpecialCuts proton

/gate/run/initialize

#/geometry/test/run

#/process/inactivate hadElastic
#/process/inactivate protonInelastic

/gate/source/addSource PBS PencilBeam
#/gate/source/PBS/setParticleType proton
/gate/source/PBS/setParticleType GenericIon
/gate/source/PBS/setIonProperties 2 4 2 0
/gate/source/PBS/setEnergy {energy} MeV
/gate/source/PBS/setSigmaEnergy 0. MeV
/gate/source/PBS/setPosition 0 0 {zbeam} mm
/gate/source/PBS/setSigmaX {spotsize} mm
/gate/source/PBS/setSigmaY {spotsize} mm
/gate/source/PBS/setRotationAxis 1 0 0
/gate/source/PBS/setRotationAngle {rotation} mrad
/gate/source/PBS/setSigmaTheta {divergence} mrad # was 3
/gate/source/PBS/setSigmaPhi {divergence} mrad # was 3
/gate/source/PBS/setEllipseXThetaEmittance {emittance} mm*mrad # was 15
/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance {emittance} mm*mrad # was 15
/gate/source/PBS/setEllipseYPhiRotationNorm negative
/gate/application/setTotalNumberOfPrimaries 10000

/gate/output/root/enable
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setRootHitFlag 1
/gate/output/root/setFileName Output/simpleScanner_energy{energy}MeV_{material}_phantom{dz}mm_Helium

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/start
