/gate/geometry/setMaterialDatabase GateMaterials.db

/gate/world/geometry/setXLength 1000. cm
/gate/world/geometry/setYLength 1000. cm
/gate/world/geometry/setZLength 1000. cm

/gate/world/daughters/name scanner
/gate/world/daughters/insert box
/gate/scanner/geometry/setXLength 500. cm
/gate/scanner/geometry/setYLength 500. cm
/gate/scanner/geometry/setZLength 500. cm
/gate/scanner/placement/setTranslation 0 0 0. cm
/gate/scanner/vis/forceWireframe

/gate/scanner/daughters/name phantom
/gate/scanner/daughters/insert box
/gate/phantom/geometry/setXLength 100. cm
/gate/phantom/geometry/setYLength 100. cm
/gate/phantom/geometry/setZLength 0.5  mm
/gate/phantom/placement/setTranslation 0 0 0 mm
/gate/phantom/setMaterial Water
/gate/phantom/vis/forceWireframe

/gate/phantom/attachCrystalSD

/gate/actor/addActor PhaseSpaceActor PSActorOut
/gate/actor/PSActorOut/save PSActorOut.root
/gate/actor/PSActorOut/attachTo phantom
/gate/actor/PSActorOut/enableEkine              true
/gate/actor/PSActorOut/enableXPosition          true
/gate/actor/PSActorOut/enableYPosition          true
/gate/actor/PSActorOut/enableZPosition          true
/gate/actor/PSActorOut/enableXDirection         true
/gate/actor/PSActorOut/enableYDirection         true
/gate/actor/PSActorOut/enableZDirection         true
/gate/actor/PSActorOut/storeOutgoingParticles   true

/gate/actor/addActor PhaseSpaceActor PSActorIn
/gate/actor/PSActorIn/save PSActorIn.root
/gate/actor/PSActorIn/attachTo phantom
/gate/actor/PSActorIn/enableEkine              true
/gate/actor/PSActorIn/enableXPosition          true
/gate/actor/PSActorIn/enableYPosition          true
/gate/actor/PSActorIn/enableZPosition          true
/gate/actor/PSActorIn/enableXDirection         true
/gate/actor/PSActorIn/enableYDirection         true
/gate/actor/PSActorIn/enableZDirection         true

/gate/physics/addPhysicsList QGSP_BIC_EMZ
/gate/geometry/setIonisationPotential Water 75 eV

/gate/physics/SetMaxStepSizeInRegion phantom 1 mm

/gate/run/initialize

/process/inactivate hadElastic
/process/inactivate protonInelastic

/gate/source/addSource PBS PencilBeam
/gate/source/PBS/setParticleType proton
/gate/source/PBS/setEnergy 230. MeV
/gate/source/PBS/setSigmaEnergy 0. MeV
/gate/source/PBS/setPosition 0 0 -20. cm
/gate/source/PBS/setSigmaX 2.5 mm
/gate/source/PBS/setSigmaY 2.5 mm
/gate/source/PBS/setSigmaTheta 3 mrad
/gate/source/PBS/setSigmaPhi 3 mrad
/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance 15 mm*mrad
/gate/source/PBS/setEllipseYPhiRotationNorm negative
/gate/application/setTotalNumberOfPrimaries 500

/gate/output/root/enable
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setFileName simpleScanner

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/start
