/gate/scanner/daughters/name doublelayer_first
/gate/scanner/daughters/insert box
/gate/doublelayer_first/geometry/setXLength 70. mm
/gate/doublelayer_first/geometry/setYLength 80. mm
/gate/doublelayer_first/geometry/setZLength 3.84 mm
/gate/doublelayer_first/placement/setTranslation 0. 0. -43.7 mm
/gate/doublelayer_first/setMaterial Air
/gate/doublelayer_first/vis/setColor black
/gate/doublelayer_first/vis/forceWireframe

/gate/doublelayer_first/daughters/name layer_first
/gate/doublelayer_first/daughters/insert box
/gate/layer_first/geometry/setXLength 60. mm
/gate/layer_first/geometry/setYLength 70. mm
/gate/layer_first/geometry/setZLength 1.9 mm
/gate/layer_first/placement/setTranslation 0. 0.5075 -0.96 mm
/gate/layer_first/setMaterial Vacuum
/gate/layer_first/vis/setColor black
/gate/layer_first/vis/forceWireframe

/gate/doublelayer_first/daughters/name layer_second
/gate/doublelayer_first/daughters/insert box
/gate/layer_second/geometry/setXLength 60. mm
/gate/layer_second/geometry/setYLength 70. mm
/gate/layer_second/geometry/setZLength 1.9 mm
/gate/layer_second/placement/setTranslation 0. -0.5075 0.96 mm
/gate/layer_second/setMaterial Vacuum
/gate/layer_second/vis/setColor black
/gate/layer_second/vis/forceWireframe

/gate/layer_second/placement/setRotationAxis 1 0 0
/gate/layer_second/placement/setRotationAngle 180 deg
#/gate/layer_second/placement/setAxis 0 1 0

/gate/layer_first/daughters/name absorber_first
/gate/layer_first/daughters/insert box
/gate/absorber_first/geometry/setXLength 50. mm
/gate/absorber_first/geometry/setYLength 49.85 mm
/gate/absorber_first/geometry/setZLength 1.5 mm
/gate/absorber_first/placement/setTranslation 0. -5.725 -0.2 mm
/gate/absorber_first/setMaterial Aluminium
/gate/absorber_first/vis/setColor yellow # Check for yellow absorber first!
/gate/absorber_first/vis/forceWireframe

/gate/layer_second/daughters/name absorber_second
/gate/layer_second/daughters/insert box
/gate/absorber_second/geometry/setXLength 50. mm
/gate/absorber_second/geometry/setYLength 49.85 mm
/gate/absorber_second/geometry/setZLength 1.5 mm
/gate/absorber_second/placement/setTranslation 0. -5.725 -0.2 mm
/gate/absorber_second/setMaterial {material}
/gate/absorber_second/vis/setColor grey
/gate/absorber_second/vis/forceWireframe

/gate/layer_first/daughters/name fillerglue_first
/gate/layer_first/daughters/insert box
/gate/fillerglue_first/geometry/setXLength 39.35 mm
/gate/fillerglue_first/geometry/setYLength 18.85 mm
/gate/fillerglue_first/geometry/setZLength 0.07 mm
/gate/fillerglue_first/placement/setTranslation 0. 9.375 0.585 mm
/gate/fillerglue_first/setMaterial Glue
/gate/fillerglue_first/vis/forceWireframe
/gate/fillerglue_first/vis/setColor yellow

/gate/layer_second/daughters/name fillerglue_second
/gate/layer_second/daughters/insert box
/gate/fillerglue_second/geometry/setXLength 39.35 mm
/gate/fillerglue_second/geometry/setYLength 18.85 mm
/gate/fillerglue_second/geometry/setZLength 0.07 mm
/gate/fillerglue_second/placement/setTranslation 0. 9.375 0.585 mm
/gate/fillerglue_second/setMaterial Glue
/gate/fillerglue_second/vis/forceWireframe
/gate/fillerglue_second/vis/setColor yellow

/gate/layer_first/daughters/name filler_first
/gate/layer_first/daughters/insert box
/gate/filler_first/geometry/setXLength 39.35 mm
/gate/filler_first/geometry/setYLength 18.85 mm
/gate/filler_first/geometry/setZLength 0.3 mm
/gate/filler_first/placement/setTranslation 0. 9.375 0.7 mm # was 9.275
/gate/filler_first/setMaterial {material}
/gate/filler_first/vis/forceWireframe
/gate/filler_first/vis/setColor grey

/gate/layer_second/daughters/name filler_second
/gate/layer_second/daughters/insert box
/gate/filler_second/geometry/setXLength 39.35 mm
/gate/filler_second/geometry/setYLength 18.85 mm
/gate/filler_second/geometry/setZLength 0.3 mm
/gate/filler_second/placement/setTranslation 0. 9.375 0.7 mm # was 9.275
/gate/filler_second/setMaterial {material}
/gate/filler_second/vis/forceWireframe
/gate/filler_second/vis/setColor grey

/gate/layer_first/daughters/name pcb_first
/gate/layer_first/daughters/insert box
/gate/pcb_first/geometry/setXLength 39.35 mm
/gate/pcb_first/geometry/setYLength 20. mm
/gate/pcb_first/geometry/setZLength 0.15 mm
/gate/pcb_first/placement/setTranslation 0. -10.05 0.625 mm
/gate/pcb_first/setMaterial PCB
/gate/pcb_first/vis/setColor green
/gate/pcb_first/vis/forceWireframe

/gate/layer_second/daughters/name pcb_second
/gate/layer_second/daughters/insert box
/gate/pcb_second/geometry/setXLength 39.35 mm
/gate/pcb_second/geometry/setYLength 20. mm
/gate/pcb_second/geometry/setZLength 0.15 mm
/gate/pcb_second/placement/setTranslation 0. -10.05 0.625 mm
/gate/pcb_second/setMaterial PCB
/gate/pcb_second/vis/setColor green
/gate/pcb_second/vis/forceWireframe

/gate/layer_first/daughters/name glue_first
/gate/layer_first/daughters/insert box
/gate/glue_first/geometry/setXLength 39.35 mm
/gate/glue_first/geometry/setYLength 20. mm
/gate/glue_first/geometry/setZLength 0.03 mm
/gate/glue_first/placement/setTranslation 0. -10.05 0.715 mm
/gate/glue_first/setMaterial Glue
/gate/glue_first/vis/setColor yellow
/gate/glue_first/vis/forceWireframe

/gate/layer_second/daughters/name glue_second
/gate/layer_second/daughters/insert box
/gate/glue_second/geometry/setXLength 39.35 mm
/gate/glue_second/geometry/setYLength 20. mm
/gate/glue_second/geometry/setZLength 0.03 mm
/gate/glue_second/placement/setTranslation 0. -10.05 0.715 mm
/gate/glue_second/setMaterial Glue
/gate/glue_second/vis/setColor yellow
/gate/glue_second/vis/forceWireframe

/gate/layer_first/daughters/name passive_first
/gate/layer_first/daughters/insert box
/gate/passive_first/geometry/setXLength 39.35 mm
/gate/passive_first/geometry/setYLength 19.7 mm
/gate/passive_first/geometry/setZLength 0.15 mm
/gate/passive_first/placement/setTranslation 0. -9.9 0.805 mm
/gate/passive_first/setMaterial Silicon
/gate/passive_first/vis/setColor white
/gate/passive_first/vis/forceWireframe

/gate/layer_second/daughters/name passive_second
/gate/layer_second/daughters/insert box
/gate/passive_second/geometry/setXLength 39.35 mm
/gate/passive_second/geometry/setYLength 19.7 mm
/gate/passive_second/geometry/setZLength 0.15 mm
/gate/passive_second/placement/setTranslation 0. -9.9 0.805 mm
/gate/passive_second/setMaterial Silicon
/gate/passive_second/vis/setColor white
/gate/passive_second/vis/forceWireframe

/gate/layer_first/daughters/name active_first
/gate/layer_first/daughters/insert box
/gate/active_first/geometry/setXLength 19.2 mm
/gate/active_first/geometry/setYLength 19.2 mm
/gate/active_first/geometry/setZLength 0.03 mm
/gate/active_first/placement/setTranslation -9.65 -10.05 0.895 mm # was x -9.85
/gate/active_first/vis/setColor yellow
/gate/active_first/vis/forceWireframe

/gate/active_first/repeaters/insert linear
/gate/active_first/linear/setRepeatNumber 2
/gate/active_first/linear/setRepeatVector 19.3 0. 0. mm
/gate/active_first/linear/autoCenter false

/gate/layer_second/daughters/name active_second
/gate/layer_second/daughters/insert box
/gate/active_second/geometry/setXLength 19.2 mm
/gate/active_second/geometry/setYLength 19.2 mm
/gate/active_second/geometry/setZLength 0.03 mm
/gate/active_second/placement/setTranslation -9.65 -10.05 0.895 mm # was x -9.85
/gate/active_second/vis/setColor red
/gate/active_second/vis/forceWireframe

/gate/active_second/repeaters/insert linear
/gate/active_second/linear/setRepeatNumber 2
/gate/active_second/linear/setRepeatVector 19.3 0. 0. mm
/gate/active_second/linear/autoCenter false

/gate/active_first/daughters/name pixels_first
/gate/active_first/daughters/insert box
/gate/pixels_first/geometry/setXLength 1.18 mm
/gate/pixels_first/geometry/setYLength 1.18 mm
/gate/pixels_first/geometry/setZLength 0.03 mm
/gate/pixels_first/placement/setTranslation -9.01 9.01 0. mm 
/gate/pixels_first/setMaterial Silicon
/gate/pixels_first/vis/setColor red
/gate/pixels_first/vis/forceWireframe

/gate/pixels_first/repeaters/insert cubicArray
/gate/pixels_first/cubicArray/setRepeatNumberX 16
/gate/pixels_first/cubicArray/setRepeatNumberY 16
/gate/pixels_first/cubicArray/setRepeatNumberZ 1
/gate/pixels_first/cubicArray/setRepeatVector 1.2 -1.2 0. mm
/gate/pixels_first/cubicArray/autoCenter false

/gate/active_second/daughters/name pixels_second
/gate/active_second/daughters/insert box
/gate/pixels_second/geometry/setXLength 1.18 mm
/gate/pixels_second/geometry/setYLength 1.18 mm
/gate/pixels_second/geometry/setZLength 0.03 mm
/gate/pixels_second/placement/setTranslation -9.01 9.01 0. mm 
/gate/pixels_second/setMaterial Silicon
/gate/pixels_second/vis/setColor red
/gate/pixels_second/vis/forceWireframe

/gate/pixels_second/repeaters/insert cubicArray
/gate/pixels_second/cubicArray/setRepeatNumberX 16
/gate/pixels_second/cubicArray/setRepeatNumberY 16
/gate/pixels_second/cubicArray/setRepeatNumberZ 1
/gate/pixels_second/cubicArray/setRepeatVector 1.2 -1.2 0. mm
/gate/pixels_second/cubicArray/autoCenter false

/gate/layer_first/daughters/name spacer_first
/gate/layer_first/daughters/insert box
/gate/spacer_first/geometry/setXLength 4. mm
/gate/spacer_first/geometry/setYLength 29. mm
/gate/spacer_first/geometry/setZLength 0.4 mm
/gate/spacer_first/placement/setTranslation -23. -16.15 0.75 mm
/gate/spacer_first/setMaterial PCB # fixme
/gate/spacer_first/vis/setColor green
/gate/spacer_first/vis/forceWireframe

/gate/spacer_first/repeaters/insert linear
/gate/spacer_first/linear/setRepeatNumber 2
/gate/spacer_first/linear/setRepeatVector 46. 0. 0. mm
/gate/spacer_first/linear/autoCenter false

/gate/layer_second/daughters/name spacer_second
/gate/layer_second/daughters/insert box
/gate/spacer_second/geometry/setXLength 4. mm
/gate/spacer_second/geometry/setYLength 29. mm
/gate/spacer_second/geometry/setZLength 0.4 mm
/gate/spacer_second/placement/setTranslation -23. -16.15 0.75 mm
/gate/spacer_second/setMaterial PCB # fixme
/gate/spacer_second/vis/setColor green
/gate/spacer_second/vis/forceWireframe

/gate/spacer_second/repeaters/insert linear
/gate/spacer_second/linear/setRepeatNumber 2
/gate/spacer_second/linear/setRepeatVector 46. 0. 0. mm
/gate/spacer_second/linear/autoCenter false

# repeat layer_first once to get 4x chip
#/gate/layer_first/repeaters/insert genericRepeater
#/gate/layer_first/genericRepeater/setPlacementsFilename geometry/layer_first.placements

#/gate/layer_second/repeaters/insert genericRepeater
#/gate/layer_second/genericRepeater/setPlacementsFilename geometry/layer_second.placements

#/gate/doublelayer_first/repeaters/insert genericRepeater
#/gate/doublelayer_first/genericRepeater/setPlacementsFilename geometry/doublelayer_first.placements
