/gate/scanner/daughters/name scintillator_F
/gate/scanner/daughters/insert box
/gate/scintillator_F/geometry/setXLength 4. cm
/gate/scintillator_F/geometry/setYLength 4. cm
/gate/scintillator_F/geometry/setZLength 1. cm
/gate/scintillator_F/placement/setTranslation 0. 0. -75. mm # 50 + 65
/gate/scintillator_F/setMaterial myScintillator
/gate/scintillator_F/vis/forceWireframe

/gate/scanner/daughters/name scintillator_H
/gate/scanner/daughters/insert box
/gate/scintillator_H/geometry/setXLength 4. cm
/gate/scintillator_H/geometry/setYLength 1. cm
/gate/scintillator_H/geometry/setZLength 0.5 cm
/gate/scintillator_H/placement/setTranslation 0. 0. -176. mm # 50 + 166
/gate/scintillator_H/setMaterial myScintillator
/gate/scintillator_H/vis/forceWireframe

/gate/scanner/daughters/name scintillator_V
/gate/scanner/daughters/insert box
/gate/scintillator_V/geometry/setXLength 1. cm
/gate/scintillator_V/geometry/setYLength 4. cm
/gate/scintillator_V/geometry/setZLength 0.5 cm
/gate/scintillator_V/placement/setTranslation 0. 0. -184. mm # 50 + 174
/gate/scintillator_V/setMaterial myScintillator
/gate/scintillator_V/vis/forceWireframe
