/gate/geometry/setMaterialDatabase GateMaterials.db

/control/execute Module_phantom.mac

/gate/systems/scanner_1/level1/attach TRACKER_Layer
/gate/systems/scanner_2/level1/attach Layer
# /gate/systems/phantom/level1/attach degrader

/gate/ALPIDEEpi/attachCrystalSD
/gate/TRACKER_ALPIDEEpi/attachCrystalSD

/gate/actor/addActor DoseActor doseDistribution
/gate/actor/doseDistribution/attachTo patient
/gate/actor/doseDistribution/setSize 192.75 165 192.75 mm 
/gate/actor/doseDistribution/setPosition 0 0 0 cm
/gate/actor/doseDistribution/setResolution 100 1 1
/gate/actor/doseDistribution/enableEdep true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep false
/gate/actor/doseDistribution/enableDose true
/gate/actor/doseDistribution/enableNumberOfHits false
/gate/actor/doseDistribution/enableSquaredDose false
/gate/actor/doseDistribution/save outputDose.root

#=================#
# Physics			#
#=================#

/gate/geometry/setIonisationPotential Water 78 eV
/gate/physics/addPhysicsList QBBC_EMZ

/gate/run/initialize

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource uniformBeam gps
/gate/source/uniformBeam/gps/particle ion
/gate/source/uniformBeam/gps/ion 2 4 2 0
/gate/source/uniformBeam/gps/ene/type Gauss
/gate/source/uniformBeam/gps/ene/mono 917 MeV
/gate/source/uniformBeam/gps/ene/sigma 0.5 MeV
/gate/source/uniformBeam/gps/type Plane
#/gate/source/uniformBeam/gps/shape Rectangle
/gate/source/uniformBeam/gps/shape Circle
/gate/source/uniformBeam/gps/direction 0 0 1
#/gate/source/uniformBeam/gps/halfx 40. mm
/gate/source/uniformBeam/gps/radius 80. mm
#/gate/source/uniformBeam/gps/halfy 40. mm
/gate/source/uniformBeam/gps/centre 0. 0. -50.0 cm

/gate/output/root/disable
#/gate/output/root/setRootSinglesFlag 0
#/gate/output/root/setFileName ../../../DTCToolkit/Data/MonteCarlo/DTC_Final_Helium_{phantom}_rotation{rotation}deg_spotx{spotx}_spoty{spoty}

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 10000 # 10k for small phantoms; 5k for head phantom
/gate/application/start
