/vis/open OGL
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 60 60
/vis/viewer/zoom 0.1
/vis/viewer/set/style wireframe
/vis/drawVolume
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
/vis/viewer/update

/gate/geometry/setMaterialDatabase GateMaterials.db

/gate/world/geometry/setXLength 300. cm
/gate/world/geometry/setYLength 300. cm
/gate/world/geometry/setZLength 300. cm
/gate/world/setMaterial Vacuum

/gate/world/daughters/name scanner
/gate/world/daughters/insert box
/gate/scanner/geometry/setXLength 200. cm
/gate/scanner/geometry/setYLength 200. cm
/gate/scanner/geometry/setZLength 200. cm
/gate/scanner/setMaterial Vacuum

/gate/scanner/daughters/name patient
/gate/scanner/daughters/insert ImageRegionalizedVolume
/gate/patient/geometry/setImage DICOM/1_dicom_125mm.dcm
/gate/patient/geometry/setHUToMaterialFile AttenuationRange.dat
#/gate/patient/geometry/TranslateTheImageAtThisIsoCenter 0 0 0 mm
/gate/patient/placement/setTranslation 0 0 0 mm
/gate/patient/placement/setRotationAxis 0 1 0
/gate/patient/placement/setRotationAngle 90 deg

/gate/patient/geometry/buildAndDumpDistanceTransfo dmap.mhd
/gate/patient/geometry/distanceMap dmap.mhd

#/gate/patient/geometry/buildAndDumpLabeledImage imageDump.hdr ## use this as setImage..?

# /gate/patient/attachPhantomSD

/gate/actor/addActor DoseActor MyActor
/gate/actor/MyActor/save actorFile.root
/gate/actor/MyActor/attachTo patient
/gate/actor/MyActor/stepHitType random
/gate/actor/MyActor/setSize 200 200 200 mm
/gate/actor/MyActor/setResolution 150 150 1
/gate/actor/MyActor/enableEdep true
/gate/actor/MyActor/enableUncertaintyEdep false
/gate/actor/MyActor/enableSquaredEdep false
/gate/actor/MyActor/enableDose false
/gate/actor/MyActor/normaliseDoseToMax false

/gate/actor/addActor SimulationStatisticActor stat
/gate/actor/stat/save stat-simulation.txt

/gate/physics/addPhysicsList QGSP_BIC_EMZ
/gate/geometry/setIonisationPotential Water 75 eV

/gate/run/initialize

/gate/source/addSource uniformBeam gps
/gate/source/uniformBeam/gps/particle proton
/gate/source/uniformBeam/gps/ene/type Gauss
/gate/source/uniformBeam/gps/ene/mono 230. MeV
/gate/source/uniformBeam/gps/ene/sigma 0. MeV
/gate/source/uniformBeam/gps/type Plane
/gate/source/uniformBeam/gps/shape Square
/gate/source/uniformBeam/gps/direction 0 0 1
/gate/source/uniformBeam/gps/halfx 100. mm
/gate/source/uniformBeam/gps/halfy 100. mm
/gate/source/uniformBeam/gps/centre 0. 0. -500 mm 

#/gate/source/addSource PBS PencilBeam
#/gate/source/PBS/setParticleType proton
#/gate/source/PBS/setEnergy 230. MeV
#/gate/source/PBS/setSigmaEnergy 0. MeV
#/gate/source/PBS/setPosition 0 0 -500. mm
#/gate/source/PBS/setSigmaX 3 mm
#/gate/source/PBS/setSigmaY 3 mm
#/gate/source/PBS/setSigmaTheta 3.3 mrad
#/gate/source/PBS/setSigmaPhi 3.8 mrad
#/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
#/gate/source/PBS/setEllipseXThetaRotationNorm negative
#/gate/source/PBS/setEllipseYPhiEmittance 20 mm*mrad
#/gate/source/PBS/setEllipseYPhiRotationNorm negative

/gate/application/setTotalNumberOfPrimaries 50000
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setRootHitFlag 1
/gate/output/root/enable
/gate/output/root/setFileName headphantom

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/start
