/gate/geometry/setMaterialDatabase GateMaterials.db

/control/execute Module_final.mac

/gate/systems/scanner_1/level1/attach TRACKER_Layer
/gate/systems/scanner_2/level1/attach Layer
/gate/systems/phantom/level1/attach degrader

/control/execute readout_final.mac

#=================#
# Physics			#
#=================#

/gate/geometry/setIonisationPotential Water 78 eV
/gate/physics/addPhysicsList QGSP_BIC_EMZ
/gate/physics/SetMaxStepSizeInRegion world 0.5 mm
/gate/physics/ActivateStepLimiter alpha

/gate/physics/Gamma/SetCutInRegion TRACKER_Glue1 2.5 um
/gate/physics/Gamma/SetCutInRegion TRACKER_Glue2 2.5 um
/gate/physics/Gamma/SetCutInRegion TRACKER_Glue3 2.5 um
/gate/physics/Gamma/SetCutInRegion TRACKER_Glue4 2.5 um
/gate/physics/Gamma/SetCutInRegion TRACKER_Absorber1 100 um
/gate/physics/Gamma/SetCutInRegion TRACKER_Absorber2 100 um
/gate/physics/Gamma/SetCutInRegion TRACKER_ALPIDESub 5 um
/gate/physics/Gamma/SetCutInRegion TRACKER_ALPIDEEpi 10 um
/gate/physics/Gamma/SetCutInRegion TRACKER_ALPIDEFront 5 um
/gate/physics/Gamma/SetCutInRegion TRACKER_AirGap1 750 um
/gate/physics/Gamma/SetCutInRegion TRACKER_AirGap2 1 mm
/gate/physics/Gamma/SetCutInRegion TRACKER_TopFDI1 15 um
/gate/physics/Gamma/SetCutInRegion TRACKER_TopFDI2 10 um
/gate/physics/Gamma/SetCutInRegion TRACKER_Spacer 40 um
/gate/physics/Gamma/SetCutInRegion TRACKER_BottomFDI1 50 um
/gate/physics/Gamma/SetCutInRegion TRACKER_BottomFDI2 10 um
/gate/physics/Gamma/SetCutInRegion Glue1 2.5 um
/gate/physics/Gamma/SetCutInRegion Glue2 2.5 um
/gate/physics/Gamma/SetCutInRegion Glue3 2.5 um
/gate/physics/Gamma/SetCutInRegion Glue4 2.5 um
/gate/physics/Gamma/SetCutInRegion Glue5 2.5 um
/gate/physics/Gamma/SetCutInRegion Absorber 500 um
/gate/physics/Gamma/SetCutInRegion ALPIDESub 30 um
/gate/physics/Gamma/SetCutInRegion ALPIDEEpi 10 um
/gate/physics/Gamma/SetCutInRegion ALPIDEFront 5 um
/gate/physics/Gamma/SetCutInRegion AirGap 750 um
/gate/physics/Gamma/SetCutInRegion TopFDI1 15 um
/gate/physics/Gamma/SetCutInRegion TopFDI2 10 um
/gate/physics/Gamma/SetCutInRegion Spacer1 130 um
/gate/physics/Gamma/SetCutInRegion Spacer2 40 um
/gate/physics/Gamma/SetCutInRegion BottomFDI1 50 um
/gate/physics/Gamma/SetCutInRegion BottomFDI2 10 um
/gate/physics/Proton/SetCutInRegion TRACKER_Glue1 2.5 um
/gate/physics/Proton/SetCutInRegion TRACKER_Glue2 2.5 um
/gate/physics/Proton/SetCutInRegion TRACKER_Glue3 2.5 um
/gate/physics/Proton/SetCutInRegion TRACKER_Glue4 2.5 um
/gate/physics/Proton/SetCutInRegion TRACKER_Absorber1 100 um
/gate/physics/Proton/SetCutInRegion TRACKER_Absorber2 100 um
/gate/physics/Proton/SetCutInRegion TRACKER_ALPIDESub 5 um
/gate/physics/Proton/SetCutInRegion TRACKER_ALPIDEEpi 10 um
/gate/physics/Proton/SetCutInRegion TRACKER_ALPIDEFront 5 um
/gate/physics/Proton/SetCutInRegion TRACKER_AirGap1 750 um
/gate/physics/Proton/SetCutInRegion TRACKER_AirGap2 1 mm
/gate/physics/Proton/SetCutInRegion TRACKER_TopFDI1 15 um
/gate/physics/Proton/SetCutInRegion TRACKER_TopFDI2 10 um
/gate/physics/Proton/SetCutInRegion TRACKER_Spacer 40 um
/gate/physics/Proton/SetCutInRegion TRACKER_BottomFDI1 50 um
/gate/physics/Proton/SetCutInRegion TRACKER_BottomFDI2 10 um
/gate/physics/Proton/SetCutInRegion Glue1 2.5 um
/gate/physics/Proton/SetCutInRegion Glue2 2.5 um
/gate/physics/Proton/SetCutInRegion Glue3 2.5 um
/gate/physics/Proton/SetCutInRegion Glue4 2.5 um
/gate/physics/Proton/SetCutInRegion Glue5 2.5 um
/gate/physics/Proton/SetCutInRegion Absorber 500 um
/gate/physics/Proton/SetCutInRegion ALPIDESub 30 um
/gate/physics/Proton/SetCutInRegion ALPIDEEpi 10 um
/gate/physics/Proton/SetCutInRegion ALPIDEFront 5 um
/gate/physics/Proton/SetCutInRegion AirGap 750 um
/gate/physics/Proton/SetCutInRegion TopFDI1 15 um
/gate/physics/Proton/SetCutInRegion TopFDI2 10 um
/gate/physics/Proton/SetCutInRegion Spacer1 130 um
/gate/physics/Proton/SetCutInRegion Spacer2 40 um
/gate/physics/Proton/SetCutInRegion BottomFDI1 50 um
/gate/physics/Proton/SetCutInRegion BottomFDI2 10 um
/gate/physics/Electron/SetCutInRegion TRACKER_Glue1 2.5 um
/gate/physics/Electron/SetCutInRegion TRACKER_Glue2 2.5 um
/gate/physics/Electron/SetCutInRegion TRACKER_Glue3 2.5 um
/gate/physics/Electron/SetCutInRegion TRACKER_Glue4 2.5 um
/gate/physics/Electron/SetCutInRegion TRACKER_Absorber1 100 um
/gate/physics/Electron/SetCutInRegion TRACKER_Absorber2 100 um
/gate/physics/Electron/SetCutInRegion TRACKER_ALPIDESub 5 um
/gate/physics/Electron/SetCutInRegion TRACKER_ALPIDEEpi 10 um
/gate/physics/Electron/SetCutInRegion TRACKER_ALPIDEFront 5 um
/gate/physics/Electron/SetCutInRegion TRACKER_AirGap1 750 um
/gate/physics/Electron/SetCutInRegion TRACKER_AirGap2 1 mm
/gate/physics/Electron/SetCutInRegion TRACKER_TopFDI1 15 um
/gate/physics/Electron/SetCutInRegion TRACKER_TopFDI2 10 um
/gate/physics/Electron/SetCutInRegion TRACKER_Spacer 40 um
/gate/physics/Electron/SetCutInRegion TRACKER_BottomFDI1 50 um
/gate/physics/Electron/SetCutInRegion TRACKER_BottomFDI2 10 um
/gate/physics/Electron/SetCutInRegion Glue1 2.5 um
/gate/physics/Electron/SetCutInRegion Glue2 2.5 um
/gate/physics/Electron/SetCutInRegion Glue3 2.5 um
/gate/physics/Electron/SetCutInRegion Glue4 2.5 um
/gate/physics/Electron/SetCutInRegion Glue5 2.5 um
/gate/physics/Electron/SetCutInRegion Absorber 500 um
/gate/physics/Electron/SetCutInRegion ALPIDESub 30 um
/gate/physics/Electron/SetCutInRegion ALPIDEEpi 10 um
/gate/physics/Electron/SetCutInRegion ALPIDEFront 5 um
/gate/physics/Electron/SetCutInRegion AirGap 750 um
/gate/physics/Electron/SetCutInRegion TopFDI1 15 um
/gate/physics/Electron/SetCutInRegion TopFDI2 10 um
/gate/physics/Electron/SetCutInRegion Spacer1 130 um
/gate/physics/Electron/SetCutInRegion Spacer2 40 um
/gate/physics/Electron/SetCutInRegion BottomFDI1 50 um
/gate/physics/Electron/SetCutInRegion BottomFDI2 10 um
/gate/physics/Positron/SetCutInRegion TRACKER_Glue1 2.5 um
/gate/physics/Positron/SetCutInRegion TRACKER_Glue2 2.5 um
/gate/physics/Positron/SetCutInRegion TRACKER_Glue3 2.5 um
/gate/physics/Positron/SetCutInRegion TRACKER_Glue4 2.5 um
/gate/physics/Positron/SetCutInRegion TRACKER_Absorber1 100 um
/gate/physics/Positron/SetCutInRegion TRACKER_Absorber2 100 um
/gate/physics/Positron/SetCutInRegion TRACKER_ALPIDESub 5 um
/gate/physics/Positron/SetCutInRegion TRACKER_ALPIDEEpi 10 um
/gate/physics/Positron/SetCutInRegion TRACKER_ALPIDEFront 5 um
/gate/physics/Positron/SetCutInRegion TRACKER_AirGap1 750 um
/gate/physics/Positron/SetCutInRegion TRACKER_AirGap2 1 mm
/gate/physics/Positron/SetCutInRegion TRACKER_TopFDI1 15 um
/gate/physics/Positron/SetCutInRegion TRACKER_TopFDI2 10 um
/gate/physics/Positron/SetCutInRegion TRACKER_Spacer 40 um
/gate/physics/Positron/SetCutInRegion TRACKER_BottomFDI1 50 um
/gate/physics/Positron/SetCutInRegion TRACKER_BottomFDI2 10 um
/gate/physics/Positron/SetCutInRegion Glue1 2.5 um
/gate/physics/Positron/SetCutInRegion Glue2 2.5 um
/gate/physics/Positron/SetCutInRegion Glue3 2.5 um
/gate/physics/Positron/SetCutInRegion Glue4 2.5 um
/gate/physics/Positron/SetCutInRegion Glue5 2.5 um
/gate/physics/Positron/SetCutInRegion Absorber 500 um
/gate/physics/Positron/SetCutInRegion ALPIDESub 30 um
/gate/physics/Positron/SetCutInRegion ALPIDEEpi 10 um
/gate/physics/Positron/SetCutInRegion ALPIDEFront 5 um
/gate/physics/Positron/SetCutInRegion AirGap 750 um
/gate/physics/Positron/SetCutInRegion TopFDI1 15 um
/gate/physics/Positron/SetCutInRegion TopFDI2 10 um
/gate/physics/Positron/SetCutInRegion Spacer1 130 um
/gate/physics/Positron/SetCutInRegion Spacer2 40 um
/gate/physics/Positron/SetCutInRegion BottomFDI1 50 um
/gate/physics/Positron/SetCutInRegion BottomFDI2 10 um

# ADD SECONDARY PRODUCTION ACTOR TO scanner_1 + scanner_2
#/gate/actor/addActor SecondaryProductionActor spa1
#/gate/actor/spa1/save spa1_graphite.root
# /gate/actor/spa1/attachTo world

/gate/run/initialize

#/process/inactivate hadElastic
#/process/inactivate protonInelastic
#/process/inactivate ionInelastic
#/process/inactivate msc

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource PBS PencilBeam
#/gate/source/PBS/setParticleType proton
/gate/source/PBS/setParticleType GenericIon
/gate/source/PBS/setIonProperties 2 4 2 0
#/gate/source/PBS/setIonProperties 6 12 6 0
/gate/source/PBS/setEnergy {energy} MeV
/gate/source/PBS/setSigmaEnergy 0. MeV
/gate/source/PBS/setPosition 0. 0. {beampos} mm
/gate/source/PBS/setSigmaX 3 mm
/gate/source/PBS/setSigmaY 3 mm
/gate/source/PBS/setSigmaTheta 2 mrad
/gate/source/PBS/setSigmaPhi 2 mrad
/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance 15 mm*mrad
/gate/source/PBS/setEllipseYPhiRotationNorm negative

#/gate/output/root/enable
#/gate/output/root/setRootSinglesFlag 0
#/gate/output/root/setFileName ../../DTCToolkit/Data/MonteCarlo/DTC_Full_Final_Helium_Degrader{degraderthickness}mm_{energy}MeV

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 1000
/gate/application/start
