/gate/geometry/setMaterialDatabase GateMaterials.db

/control/execute Module_final_auto.mac

/gate/systems/scanner_1/level1/attach TRACKER_Layer
/gate/systems/scanner_2/level1/attach Layer
/gate/systems/phantom/level1/attach degrader

/control/execute readout_full_final.mac
#/gate/world/attachCrystalSD

#=================#
# Physics			#
#=================#

/gate/geometry/setIonisationPotential Water 78 eV
/gate/physics/addPhysicsList QBBC_EMZ
/gate/physics/SetMaxStepSizeInRegion world 1 mm
/gate/physics/ActivateStepLimiter alpha
/gate/physics/Gamma/SetCutInRegion TRACKER_ALPIDEEpi 10 um
/gate/physics/Gamma/SetCutInRegion ALPIDEEpi 10 um
/gate/physics/Proton/SetCutInRegion TRACKER_ALPIDEEpi 10 um
/gate/physics/Proton/SetCutInRegion ALPIDEEpi 10 um
/gate/physics/Electron/SetCutInRegion TRACKER_ALPIDEEpi 10 um
/gate/physics/Electron/SetCutInRegion ALPIDEEpi 10 um
/gate/physics/Positron/SetCutInRegion TRACKER_ALPIDEEpi 10 um
/gate/physics/Positron/SetCutInRegion ALPIDEEpi 10 um

#/gate/actor/addActor PhaseSpaceActor psa
#/gate/actor/psa/save ../../DTCToolkit/Data/MonteCarlo/DTC_Full_Final_Helium_Degrader{degraderthickness}mm_{energy}MeV_psa.root
#/gate/actor/psa/attachTo psaVolume
#/gate/actor/psa/enableEkine true
#/gate/actor/psa/enableXPosition false
#/gate/actor/psa/enableYPosition false
#/gate/actor/psa/enableZPosition false
#/gate/actor/psa/enableXDirection false
#/gate/actor/psa/enableYDirection false
#/gate/actor/psa/enableZDirection false
#/gate/actor/psa/enableProductionVolume false
#/gate/actor/psa/enableProductionProcess false
#/gate/actor/psa/enableParticleName false
#/gate/actor/psa/enableWeight false
#/gate/actor/psa/storeSecondaries false

# Should cross check this with uniform cuts in all regions !!
/gate/run/initialize

#/process/inactivate hadElastic
#/process/inactivate protonInelastic
#/process/inactivate alphaInelastic
#/process/inactivate ionInelastic
#/process/inactivate msc

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource PBS PencilBeam
#/gate/source/PBS/setParticleType proton
/gate/source/PBS/setParticleType GenericIon
/gate/source/PBS/setIonProperties 2 4 2 0
#/gate/source/PBS/setIonProperties 6 12 6 0
/gate/source/PBS/setEnergy {energy} MeV
/gate/source/PBS/setSigmaEnergy 0. MeV
/gate/source/PBS/setPosition 0. 0. -500 mm
/gate/source/PBS/setSigmaX 3 mm
/gate/source/PBS/setSigmaY 3 mm
/gate/source/PBS/setSigmaTheta 2 mrad
/gate/source/PBS/setSigmaPhi 2 mrad
/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance 15 mm*mrad
/gate/source/PBS/setEllipseYPhiRotationNorm negative

/gate/output/root/enable
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setFileName ../../DTCToolkit/Data/MonteCarlo/DTC_Full_Final_Helium_Degrader{degraderthickness}mm_{energy}MeV

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 100000
/gate/application/start
