#===============================#
# FOCAL prototype		#
# First try at doing the	#
# simulation in GATE.		#
# Based on technical drawings	#
# and different MSc theses.	#
#				#
#            Helge Pettersen	#
#         me@helgepettersen.no	#
#     FEB 2015			#
#===============================#

#=======================#
#   Some aliases	#
#=======================#
#/control/alias chip0 /vis/viewer/panTo -0.02 -0.01


/vis/open OGL
#/vis/open OGLSQt
/vis/viewer/reset
/vis/viewer/panTo 0.03 -0.05
/vis/viewer/zoom 5
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/set/style surface
/vis/drawVolume
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate 25
#/vis/scene/add/trajectories
/vis/viewer/update

/gate/geometry/setMaterialDatabase GateMaterials.db

#=======================#
#    Load geometry	#
#	- AND -		#
# Attach geometry to	#
# system type 'scanner'	#
#=======================#

/control/execute geometry_script.mac

/gate/scanner/vis/setColor black
/gate/doublelayer/vis/setColor black

/gate/systems/scanner/level1/attach doublelayer
/gate/systems/scanner/level2/attach layer
/gate/systems/scanner/level3/attach active
/gate/systems/scanner/level4/attach pixels

#===============================#
# Add sensitive detectors	#
# Only added to the pixel unit	#
#===============================#

/gate/pixels/attachCrystalSD

#/gate/digitizer/Singles/insert adder
#/gate/digitizer/Singles/insert readout
#/gate/digitizer/Singles/readout/setDepth 3
#/gate/digitizer/Singles/insert thresholder
#/gate/digitizer/Singles/thresholder/setThreshold 1. keV # find a good number

#===============#
# Physics	#
#===============#

/gate/geometry/setIonisationPotential Water 75 eV
/gate/physics/addPhysicsList emstandard_opt3

#/gate/physics/addProcess SingleScattering proton

/gate/physics/SetMaxStepSizeInRegion      scanner {step_active} um
/gate/physics/SetMaxStepSizeInRegion	   absorber {step_passive} um
/gate/physics/SetMaxStepSizeInRegion      filler {step_passive} um
#
/gate/physics/ActivateStepLimiter         charged
/gate/physics/ActivateStepLimiter         gamma
/gate/physics/ActivateStepLimiter         proton
#
/gate/physics/Electron/SetCutInRegion  scanner {step_active} um
/gate/physics/Positron/SetCutInRegion  scanner {step_active} um
/gate/physics/Gamma/SetCutInRegion     scanner {step_active} um
/gate/physics/Proton/SetCutInRegion    scanner {step_active} um
#
/gate/physics/Electron/SetCutInRegion  absorber {step_passive} um
/gate/physics/Positron/SetCutInRegion  absorber {step_passive} um
/gate/physics/Gamma/SetCutInRegion     absorber {step_passive} um
##
/gate/physics/Electron/SetCutInRegion  filler {step_passive} um
/gate/physics/Positron/SetCutInRegion  filler {step_passive} um
/gate/physics/Gamma/SetCutInRegion     filler {step_passive} um

#/gate/physics/Electron/SetCutInRegion  frontabsorber {step_passive} um
#/gate/physics/Positron/SetCutInRegion  frontabsorber {step_passive} um
#/gate/physics/Gamma/SetCutInRegion     frontabsorber {step_passive} um
#
/gate/physics/Electron/SetCutInRegion  spacer {step_passive} um
/gate/physics/Positron/SetCutInRegion  spacer {step_passive} um
/gate/physics/Gamma/SetCutInRegion     spacer {step_passive} um

/gate/run/initialize

# Geometry is unaltered since last time
#/geometry/test/recursive_test

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource uniformBeam gps
/gate/source/uniformBeam/gps/particle proton
/gate/source/uniformBeam/gps/ene/type Gauss
/gate/source/uniformBeam/gps/ene/mono {energy} MeV
/gate/source/uniformBeam/gps/ene/sigma {sigma} MeV
/gate/source/uniformBeam/gps/type Plane
/gate/source/uniformBeam/gps/shape Square
/gate/source/uniformBeam/gps/direction 0 0 1
/gate/source/uniformBeam/gps/halfx 20. mm
/gate/source/uniformBeam/gps/halfy 20. mm
/gate/source/uniformBeam/gps/centre 0. 0. -6.0 cm # -20 cm for scintillator

#/gate/source/addSource PBS PencilBeam
#/gate/source/PBS/setParticleType proton
#/gate/source/PBS/setEnergy {energy} MeV
#/gate/source/PBS/setSigmaEnergy 0. MeV
#/gate/source/PBS/setPosition 0. 0. -5.2 cm
#/gate/source/PBS/setSigmaX 7. mm
#/gate/source/PBS/setSigmaY 7. mm
#/gate/source/PBS/setSigmaTheta 0.1 mrad
#/gate/source/PBS/setSigmaPhi 0.1 mrad
#/gate/source/PBS/setEllipseXThetaEmittance 1 mm*mrad
#/gate/source/PBS/setEllipseYPhiEmittance 1 mm*mrad
#/gate/source/PBS/setEllipseXThetaRotationNorm positive
#/gate/source/PBS/setEllipseYPhiRotationNorm positive

#=======================#
# Add output		#
#=======================#

#/gate/output/ascii/disable
#/gate/output/ascii/setFileName output/test

# Enable ASCII output for hits
#/gate/output/ascii/setOutFileHitsFlag 0

# Enable ASCII output for Singles (end of digitizer chain)
#/gate/output/ascii/setOutFileSinglesFlag 0

# Enable ASCII output for singles (after a digitizer module)
#/gate/output/ascii/setOutFileSinglesAdderFlag 0
#/gate/output/ascii/setOutFileSinglesReadoutFlag 0
#/gate/output/ascii/setOutFileSinglesThresholderFlag 0

# Enable ROOT output
/gate/output/root/enable
/gate/output/root/setFileName ../focalCode/rawdata/test_tracks_sigma{sigma}_{material}_{energy}MeV

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries {npart}
/gate/application/start
exit
