/vis/open OGL
/vis/viewer/reset
# /vis/viewer/panTo 0.04 -0.05
/vis/viewer/zoom 8
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/set/style surface
/vis/drawVolume
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate 25
#/vis/scene/add/trajectories
/vis/viewer/update

/gate/geometry/setMaterialDatabase GateMaterials.db

/control/execute geometry/main.mac

/gate/systems/scanner/level1/attach simplified
/gate/systems/scanner/level2/attach layer
/gate/systems/scanner/level3/attach chip

/control/execute readout_chip.mac
#/control/execute readout_chip_scintillators.mac
#/control/execute readout_full.mac

#=================#
# Physics			#
#=================#

/gate/geometry/setIonisationPotential Water 75 eV
/gate/physics/addPhysicsList QGSP_BIC_EMY
# What about QGSP_BIC_HP_EMY? What does HP do? It's the recommended one @ the GATE workshop.

#/gate/physics/addProcess SingleScattering proton

#/gate/physics/SetMaxStepSizeInRegion      scanner {step_passive} um
#/gate/physics/SetMaxStepSizeInRegion	   chip {step_active} um

#/gate/physics/ActivateStepLimiter         charged
#/gate/physics/ActivateStepLimiter         gamma
#/gate/physics/ActivateStepLimiter         proton

#gate/physics/Electron/SetCutInRegion  scanner {step_passive} mm
#gate/physics/Positron/SetCutInRegion  scanner {step_passive} mm
#gate/physics/Gamma/SetCutInRegion     scanner {step_passive} mm
#gate/physics/Proton/SetCutInRegion    scanner {step_passive} mm

#gate/physics/Electron/SetCutInRegion  chip {step_active} um
#gate/physics/Positron/SetCutInRegion  chip {step_active} um
#gate/physics/Gamma/SetCutInRegion     chip {step_active} um
#gate/physics/Proton/SetCutInRegion    chip {step_active} um

/gate/run/initialize

# /geometry/test/recursive_test

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource uniformBeam gps
/gate/source/uniformBeam/gps/particle proton
/gate/source/uniformBeam/gps/ene/type Gauss
/gate/source/uniformBeam/gps/ene/mono {energy} MeV
/gate/source/uniformBeam/gps/ene/sigma {sigma} MeV
/gate/source/uniformBeam/gps/type Plane
/gate/source/uniformBeam/gps/shape Square
/gate/source/uniformBeam/gps/direction 0 0 1
/gate/source/uniformBeam/gps/halfx 20. mm
/gate/source/uniformBeam/gps/halfy 20. mm
/gate/source/uniformBeam/gps/centre 0. 0. -20.0 cm

#/gate/source/addSource PBS PencilBeam
#/gate/source/PBS/setParticleType proton
#/gate/source/PBS/setEnergy {energy} MeV
#/gate/source/PBS/setSigmaEnergy 0. MeV
#/gate/source/PBS/setPosition 0. 0. -5.2 cm
#/gate/source/PBS/setSigmaX 7. mm
#/gate/source/PBS/setSigmaY 7. mm
#/gate/source/PBS/setSigmaTheta 0.1 mrad
#/gate/source/PBS/setSigmaPhi 0.1 mrad
#/gate/source/PBS/setEllipseXThetaEmittance 1 mm*mrad
#/gate/source/PBS/setEllipseYPhiEmittance 1 mm*mrad
#/gate/source/PBS/setEllipseXThetaRotationNorm positive
#/gate/source/PBS/setEllipseYPhiRotationNorm positive

/gate/output/root/enable
/gate/output/root/setFileName ../focalCode/rawdata/focal_{material}_energy{energy}_sigma{sigma}

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries {npart}
/gate/application/start
#exit
