#===============================#
# FOCAL prototype		#
# First try at doing the	#
# simulation in GATE.		#
# Based on technical drawings	#
# and different MSc theses.	#
#				#
#            Helge Pettersen	#
#         me@helgepettersen.no	#
#     FEB 2015			#
#===============================#

#=======================#
#   Some aliases	#
#=======================#
/control/alias chip0 /vis/viewer/panTo -0.02 -0.01


/vis/open OGL
#/vis/open OGLSQt
/vis/viewer/reset
/vis/viewer/zoom 5
/vis/viewer/panTo 0.03 -0.05
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/set/style surface
/vis/drawVolume
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate 25
#/vis/scene/add/trajectories
/vis/viewer/update

/gate/geometry/setMaterialDatabase GateMaterials.db

#=======================#
#    Load geometry	#
#	- AND -		#
# Attach geometry to	#
# system type 'scanner'	#
#=======================#

/control/execute geometry.mac

/gate/scanner/vis/setColor black
/gate/doublelayer/vis/setColor black

/gate/systems/scanner/level1/attach doublelayer
/gate/systems/scanner/level2/attach layer
/gate/systems/scanner/level3/attach active
/gate/systems/scanner/level4/attach pixels


#===============================#
# Add sensitive detectors	#
# Only added to the pixel unit	#
#===============================#

/gate/pixels/attachCrystalSD
#/gate/absorber/attachCrystalSD
#/gate/filler/attachCrystalSD
#/gate/frontabsorber/attachCrystalSD
#/gate/phantom/attachCrystalSD

#/gate/doublelayer/attachCrystalSD

#/gate/digitizer/Singles/insert adder
#/gate/digitizer/Singles/insert readout
#/gate/digitizer/Singles/readout/setDepth 3
#/gate/digitizer/Singles/insert thresholder
#/gate/digitizer/Singles/thresholder/setThreshold 1. keV # find a good number

#===============#
# Physics	#
#===============#

# Penelope model for low energy EM
#/gate/physics/addPhysicsList emstandard_opt1 # urban MCS model

# Single scattering??

# Binary cascade, precompound, de-excitation model for hadrons
# Standard EM
# Recommended for use at energies below 200 MeV (medical)

# we test for NO HADRONIC PHYSICS

#/gate/physics/addPhysicsList emstandard_opt3
#/gate/physics/addPhysicsList QGSP_BERT_EMV
/gate/physics/addPhysicsList QGSP_INCLXX
/gate/physics/addProcess SingleScattering proton

# thresholds 0.05 mm ... ?
#/gate/physics/Gamma/SetCutInRegion		   world	0.5 mm
#/gate/physics/Electron/SetCutInRegion	   world 0.5 mm
#/gate/physics/Positron/SetCutInRegion	   world	0.5 mm
#/gate/physics/Proton/SetCutInRegion		   world 0.5 mm
#/gate/physics/SetMaxStepSizeInRegion	   absorber 50 um
#/gate/physics/SetMaxStepSizeInRegion     filler 50 um
#/gate/physics/SetMaxStepSizeInRegion     frontabsorber 50 um
#/gate/physics/SetMaxStepSizeInRegion     spacer 50 um
#/gate/physics/SetMaxStepSizeInRegion     pcb 50 um
#/gate/physics/SetMaxStepSizeInRegion     glue 50 um
/gate/physics/SetMaxStepSizeInRegion      scanner 10 um
/gate/physics/ActivateStepLimiter         charged
/gate/physics/ActivateStepLimiter         gamma
/gate/physics/ActivateStepLimiter         proton

/gate/physics/Electron/SetCutInRegion  scanner 10 um
/gate/physics/Positron/SetCutInRegion  scanner 10 um
/gate/physics/Gamma/SetCutInRegion     scanner 10 um
/gate/physics/Proton/SetCutInRegion    scanner 10 um

#/gate/physics/Electron/SetCutInRegion   active 5 um
#/gate/physics/Positron/SetCutInRegion   active 5 um
#/gate/physics/Gamma/SetCutInRegion     active 5 um
#
#/gate/physics/Electron/SetCutInRegion   passive 50 um
#/gate/physics/Positron/SetCutInRegion   passive 50 um
#/gate/physics/Gamma/SetCutInRegion     passive 50 um
#
#/gate/physics/Electron/SetCutInRegion   pcb 50 um
#/gate/physics/Positron/SetCutInRegion   pcb 50 um
#/gate/physics/Gamma/SetCutInRegion     pcb 50 um
#
#/gate/physics/Electron/SetCutInRegion   glue 50 um
#/gate/physics/Positron/SetCutInRegion   glue 50 um
#/gate/physics/Gamma/SetCutInRegion     glue 50 um
#
#/gate/physics/Electron/SetCutInRegion   absorber 300 um
#/gate/physics/Positron/SetCutInRegion   absorber 300 um
#/gate/physics/Gamma/SetCutInRegion     absorber 300 um
#
#/gate/physics/Electron/SetCutInRegion   filler 300 um
#/gate/physics/Positron/SetCutInRegion   filler 300 um
#/gate/physics/Gamma/SetCutInRegion     filler 300 um
#
#/gate/physics/Electron/SetCutInRegion   frontabsorber 300 um
#/gate/physics/Positron/SetCutInRegion   frontabsorber 300 um
#/gate/physics/Gamma/SetCutInRegion     frontabsorber 300 um
#
#/gate/physics/Electron/SetCutInRegion   spacer 300 um
#/gate/physics/Positron/SetCutInRegion   spacer 300 um
#/gate/physics/Gamma/SetCutInRegion     spacer 300 um

/gate/run/initialize

# Geometry is unaltered since last time
#/geometry/test/recursive_test

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource PBS PencilBeam
/gate/source/PBS/setParticleType proton
/gate/source/PBS/setEnergy 150. MeV
#/gate/source/PBS/setEnergy 260. MeV
/gate/source/PBS/setSigmaEnergy 0. MeV
#/gate/source/PBS/setPosition 0. 0. -25. cm
/gate/source/PBS/setPosition 0. 0. -5.2 cm
/gate/source/PBS/setSigmaX 10. mm
/gate/source/PBS/setSigmaY 10. mm
/gate/source/PBS/setSigmaTheta 0.1 mrad
/gate/source/PBS/setSigmaPhi 0.1 mrad
/gate/source/PBS/setEllipseXThetaEmittance 1 mm*mrad
/gate/source/PBS/setEllipseYPhiEmittance 1 mm*mrad
/gate/source/PBS/setEllipseXThetaRotationNorm positive
/gate/source/PBS/setEllipseYPhiRotationNorm positive

#=======================#
# Add output		#
#=======================#

#/gate/output/ascii/disable
#/gate/output/ascii/setFileName output/test

# Enable ASCII output for hits
#/gate/output/ascii/setOutFileHitsFlag 0

# Enable ASCII output for Singles (end of digitizer chain)
#/gate/output/ascii/setOutFileSinglesFlag 0

# Enable ASCII output for singles (after a digitizer module)
#/gate/output/ascii/setOutFileSinglesAdderFlag 0
#/gate/output/ascii/setOutFileSinglesReadoutFlag 0
#/gate/output/ascii/setOutFileSinglesThresholderFlag 0

# Enable ROOT output
/gate/output/root/enable
/gate/output/root/setFileName ../focalCode/testW150MeV

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 4000
/gate/application/start
