#/vis/open OGL #1000x1000-0+0
#/vis/viewer/reset
#/vis/drawVolume
#/vis/viewer/zoom 2
#/vis/viewer/set/viewpointThetaPhi 200 -30 # 90 0
#/vis/viewer/set/style surface
#/vis/viewer/set/hiddenEdge true
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate 25
#/vis/scene/add/trajectories
#/vis/viewer/update

/gate/geometry/setMaterialDatabase GateMaterials.db

/control/execute Module.mac

/gate/systems/scanner/level1/attach Layer
/gate/systems/scanner/level2/attach Module

/gate/ActiveChipLeft/attachCrystalSD
/gate/FM_ActiveChipLeft/attachCrystalSD
/gate/ActiveChipRight/attachCrystalSD
/gate/FM_ActiveChipRight/attachCrystalSD

#=================#
# Physics			#
#=================#

/gate/geometry/setIonisationPotential Water 75 eV
/gate/physics/addPhysicsList QGSP_BIC_EMY

/gate/run/initialize

#/geometry/test/recursive_test

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource uniformBeam gps
/gate/source/uniformBeam/gps/particle proton
/gate/source/uniformBeam/gps/ene/type Gauss
/gate/source/uniformBeam/gps/ene/mono 150 MeV
/gate/source/uniformBeam/gps/ene/sigma 0 MeV
/gate/source/uniformBeam/gps/type Plane
/gate/source/uniformBeam/gps/shape Square
/gate/source/uniformBeam/gps/direction 0 0 1
/gate/source/uniformBeam/gps/halfx 20. mm
/gate/source/uniformBeam/gps/halfy 20. mm
/gate/source/uniformBeam/gps/centre 0. 0. -30.0 cm

/gate/output/root/enable
/gate/output/root/setFileName pythonTest

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 4000
/gate/application/start
