#/vis/open DAWNFILE
#/vis/viewer/reset
#/vis/viewer/set/viewpointThetaPhi 30 0
#/vis/viewer/zoom 1.5
#/vis/drawVolume
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
#/vis/viewer/update /vis/viewer/refresh 

/gate/geometry/setMaterialDatabase GateMaterials.db
/control/execute Module.mac

/gate/systems/scanner_1/level1/attach FM_Layer
/gate/systems/scanner_1/level2/attach FirstModule
/gate/systems/scanner_2/level1/attach Layer
/gate/systems/scanner_2/level2/attach Module
/gate/systems/phantom/level1/attach degrader

#/control/execute readout.mac
/control/execute readout_full.mac

#=================#
# Physics			#
#=================#

/gate/geometry/setIonisationPotential Water 75 eV
/gate/physics/addPhysicsList QGSP_BIC_EMY

/gate/run/initialize

#/geometry/test/recursive_test
/geometry/test/run

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource uniformBeam gps
/gate/source/uniformBeam/gps/particle proton
/gate/source/uniformBeam/gps/ene/type Gauss
/gate/source/uniformBeam/gps/ene/mono {energy} MeV
/gate/source/uniformBeam/gps/ene/sigma 0 MeV
/gate/source/uniformBeam/gps/type Plane
/gate/source/uniformBeam/gps/shape Square
/gate/source/uniformBeam/gps/direction 0 0 1
/gate/source/uniformBeam/gps/halfx 0. mm
/gate/source/uniformBeam/gps/halfy 0. mm
/gate/source/uniformBeam/gps/centre 0. 0. {beampos} cm

/gate/output/root/enable
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setFileName ../../DTCToolkit/Data/MonteCarlo/DTC_Full_Aluminium_Absorber{absorberthickness}mm_Degrader{degraderthickness}mm_{energy}MeV

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 5000
/gate/application/start
