#/vis/open OGL #1000x1000-0+0
#/vis/viewer/reset
#/vis/drawVolume
#/vis/viewer/zoom 2
#/vis/viewer/set/style surface
#/vis/viewer/set/hiddenEdge true
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate 25
#/vis/scene/add/trajectories
#/vis/viewer/update

/gate/geometry/setMaterialDatabase GateMaterials.db

/control/execute Module.mac

/gate/systems/scanner_1/level1/attach FM_Layer
/gate/systems/scanner_2/level1/attach Layer
/gate/systems/scanner_1/level2/attach FirstModule
/gate/systems/scanner_2/level2/attach Module

/gate/FM_ActiveChipLeft/attachCrystalSD
/gate/FM_ActiveChipRight/attachCrystalSD
/gate/ActiveChipLeft/attachCrystalSD
/gate/ActiveChipRight/attachCrystalSD

#/control/execute readout_full.mac

#=================#
# Physics			#
#=================#

/gate/geometry/setIonisationPotential Water 75 eV
/gate/physics/addPhysicsList QGSP_BIC_EMY

/gate/run/initialize

#/geometry/test/recursive_test
#/geometry/test/run

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource uniformBeam gps
/gate/source/uniformBeam/gps/particle proton
/gate/source/uniformBeam/gps/ene/type Gauss
/gate/source/uniformBeam/gps/ene/mono {energy} MeV
/gate/source/uniformBeam/gps/ene/sigma 0 MeV
/gate/source/uniformBeam/gps/type Plane
/gate/source/uniformBeam/gps/shape Square
/gate/source/uniformBeam/gps/direction 0 0 1
/gate/source/uniformBeam/gps/halfx 20. mm
/gate/source/uniformBeam/gps/halfy 20. mm
/gate/source/uniformBeam/gps/centre 0. 0. -3.0 cm

/gate/output/root/enable
/gate/output/root/setFileName ../../focalCode/Data/MonteCarlo/optimize_{energy}MeV_{absorberthickness}mm

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 25000
/gate/application/start
