#/vis/open DAWNFILE
#/vis/viewer/reset
#/vis/viewer/set/viewpointThetaPhi 30 0
#/vis/viewer/zoom 1.5
#/vis/drawVolume
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
#/vis/viewer/update /vis/viewer/refresh 

/gate/geometry/setMaterialDatabase GateMaterials.db
/control/execute Module.mac

/gate/systems/scanner_1/level1/attach FM_Layer
/gate/systems/scanner_1/level2/attach FirstModule
/gate/systems/scanner_2/level1/attach Layer
/gate/systems/scanner_2/level2/attach Module
/gate/systems/phantom/level1/attach degrader

/control/execute readout.mac

#=================#
# Physics			#
#=================#

/gate/geometry/setIonisationPotential Water 75 eV
/gate/physics/addPhysicsList QGSP_BIC_EMY

/gate/run/initialize

#/process/inactivate hadElastic
#/process/inactivate protonInelastic

/process/list

#/geometry/test/recursive_test
/geometry/test/run

#=======================#
# ADD PROTON BEAM	      #
#=======================#

/gate/source/addSource PBS PencilBeam
/gate/source/PBS/setParticleType proton
/gate/source/PBS/setEnergy 250. MeV
/gate/source/PBS/setSigmaEnergy 0. MeV
/gate/source/PBS/setPosition 0. 0. {beampos} mm
/gate/source/PBS/setSigmaX 4 mm
/gate/source/PBS/setSigmaY 2 mm
/gate/source/PBS/setSigmaTheta 3.3 mrad
/gate/source/PBS/setSigmaPhi 3.8 mrad
/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance 20 mm*mrad
/gate/source/PBS/setEllipseYPhiRotationNorm negative

#/gate/source/addSource uniformBeam gps
#/gate/source/uniformBeam/gps/particle proton
#/gate/source/uniformBeam/gps/ene/type Gauss
#/gate/source/uniformBeam/gps/ene/mono {energy} MeV
#/gate/source/uniformBeam/gps/ene/sigma 0 MeV
#/gate/source/uniformBeam/gps/type Plane
##/gate/source/uniformBeam/gps/shape Square
#/gate/source/uniformBeam/gps/shape Circle
#/gate/source/uniformBeam/gps/direction 0 0 1
#/gate/source/uniformBeam/gps/radius 2. mm
##/gate/source/uniformBeam/gps/halfx 70.71 mm
##/gate/source/uniformBeam/gps/halfy 35.355 mm
#/gate/source/uniformBeam/gps/halfx 0 mm
#/gate/source/uniformBeam/gps/halfy 0 mm
#/gate/source/uniformBeam/gps/centre 0. 0. {beampos} mm

/gate/output/root/enable
/gate/output/root/setRootSinglesFlag 0
/gate/output/root/setFileName ../../DTCToolkit/Data/MonteCarlo/DTC_Aluminium_Absorber{absorberthickness}mm_Degrader{degraderthickness}mm_{energy}MeV_4x2
#/gate/output/root/setFileName ../../DTCToolkit/Data/MonteCarlo/DTC_Tungsten_Absorber{absorberthickness}mm_Degrader{degraderthickness}mm_{energy}MeV
#/gate/output/root/setFileName ../../projects/Tracking/Data/RealisticPencilBeamThrough20cmWaterPhantom.root

#===============#
# START BEAMS	#
#===============#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 50000
/gate/application/start
