/gate/world/geometry/setXLength 3500.0 mm
/gate/world/geometry/setYLength 1500.0 mm
/gate/world/geometry/setZLength 3500.0 mm
/gate/world/placement/setTranslation 0 0 0 mm
/gate/world/vis/setVisible false

/gate/world/daughters/name scanner_1
/gate/world/daughters/systemType scanner
/gate/world/daughters/insert box
/gate/scanner_1/geometry/setXLength 150.0 mm
/gate/scanner_1/geometry/setYLength 150.0 mm
/gate/scanner_1/geometry/setZLength 0.975 mm
/gate/scanner_1/placement/setTranslation 0 0 0.4875 mm
/gate/scanner_1/vis/setVisible false

/gate/scanner_1/daughters/name FM_Layer
/gate/scanner_1/daughters/insert box
/gate/FM_Layer/geometry/setXLength 60.0 mm
/gate/FM_Layer/geometry/setYLength 60.0 mm
/gate/FM_Layer/geometry/setZLength 0.975 mm
/gate/FM_Layer/placement/setTranslation 0 0 0 mm
/gate/FM_Layer/vis/setVisible false

/gate/FM_Layer/daughters/name FirstModule
/gate/FM_Layer/daughters/insert box
/gate/FirstModule/geometry/setXLength 60.0 mm
/gate/FirstModule/geometry/setYLength 60.0 mm
/gate/FirstModule/geometry/setZLength 0.44995 mm
/gate/FirstModule/placement/setTranslation 0 0 -0.2625 mm
/gate/FirstModule/vis/setVisible false

/gate/FirstModule/repeaters/insert genericRepeater
/gate/FirstModule/genericRepeater/setPlacementsFilename Module.placements

/gate/FirstModule/daughters/name FM_PCBGlue
/gate/FirstModule/daughters/insert box
/gate/FM_PCBGlue/geometry/setXLength 38.39 mm
/gate/FM_PCBGlue/geometry/setYLength 19.145 mm
/gate/FM_PCBGlue/geometry/setZLength 0.0399 mm
/gate/FM_PCBGlue/placement/setTranslation 0 9.5725 -0.205 mm
/gate/FM_PCBGlue/setMaterial Glue
/gate/FM_PCBGlue/vis/setColor yellow

/gate/FirstModule/daughters/name FM_PCB
/gate/FirstModule/daughters/insert box
/gate/FM_PCB/geometry/setXLength 38.39 mm
/gate/FM_PCB/geometry/setYLength 19.145 mm
/gate/FM_PCB/geometry/setZLength 0.1599 mm
/gate/FM_PCB/placement/setTranslation 0 9.5725 -0.105 mm
/gate/FM_PCB/setMaterial PCB
/gate/FM_PCB/vis/setColor green

/gate/FirstModule/daughters/name FM_ChipGlue
/gate/FirstModule/daughters/insert box
/gate/FM_ChipGlue/geometry/setXLength 38.39 mm
/gate/FM_ChipGlue/geometry/setYLength 19.145 mm
/gate/FM_ChipGlue/geometry/setZLength 0.0399 mm
/gate/FM_ChipGlue/placement/setTranslation 0 9.5725 -0.005 mm
/gate/FM_ChipGlue/setMaterial Glue
/gate/FM_ChipGlue/vis/setColor yellow

/gate/FirstModule/daughters/name FM_PassiveChipLeft
/gate/FirstModule/daughters/insert box
/gate/FM_PassiveChipLeft/geometry/setXLength 19.145 mm
/gate/FM_PassiveChipLeft/geometry/setYLength 19.145 mm
/gate/FM_PassiveChipLeft/geometry/setZLength 0.1058 mm
/gate/FM_PassiveChipLeft/placement/setTranslation -9.6225 9.5725 0.068 mm
/gate/FM_PassiveChipLeft/setMaterial Silicon
/gate/FM_PassiveChipLeft/vis/setColor blue

/gate/FirstModule/daughters/name FM_PassiveChipRight
/gate/FirstModule/daughters/insert box
/gate/FM_PassiveChipRight/geometry/setXLength 19.145 mm
/gate/FM_PassiveChipRight/geometry/setYLength 19.145 mm
/gate/FM_PassiveChipRight/geometry/setZLength 0.1058 mm
/gate/FM_PassiveChipRight/placement/setTranslation 9.6225 9.5725 0.068 mm
/gate/FM_PassiveChipRight/setMaterial Silicon
/gate/FM_PassiveChipRight/vis/setColor blue

/gate/FirstModule/daughters/name FM_ActiveChipLeft
/gate/FirstModule/daughters/insert box
/gate/FM_ActiveChipLeft/geometry/setXLength 19.145 mm
/gate/FM_ActiveChipLeft/geometry/setYLength 19.145 mm
/gate/FM_ActiveChipLeft/geometry/setZLength 0.0138 mm
/gate/FM_ActiveChipLeft/placement/setTranslation -9.6225 9.5725 0.128 mm
/gate/FM_ActiveChipLeft/setMaterial Silicon
/gate/FM_ActiveChipLeft/vis/setColor red

/gate/FirstModule/daughters/name FM_ActiveChipRight
/gate/FirstModule/daughters/insert box
/gate/FM_ActiveChipRight/geometry/setXLength 19.145 mm
/gate/FM_ActiveChipRight/geometry/setYLength 19.145 mm
/gate/FM_ActiveChipRight/geometry/setZLength 0.0138 mm
/gate/FM_ActiveChipRight/placement/setTranslation 9.6225 9.5725 0.128 mm
/gate/FM_ActiveChipRight/setMaterial Silicon
/gate/FM_ActiveChipRight/vis/setColor red

/gate/FirstModule/daughters/name FM_AirGapAfterChip
/gate/FirstModule/daughters/insert box
/gate/FM_AirGapAfterChip/geometry/setXLength 38.39 mm
/gate/FM_AirGapAfterChip/geometry/setYLength 19.145 mm
/gate/FM_AirGapAfterChip/geometry/setZLength 0.0899 mm
/gate/FM_AirGapAfterChip/placement/setTranslation 0 9.5725 0.18 mm
/gate/FM_AirGapAfterChip/setMaterial Air
/gate/FM_AirGapAfterChip/vis/setVisible false

/gate/FirstModule/daughters/name FM_AirGapAfterFiller
/gate/FirstModule/daughters/insert box
/gate/FM_AirGapAfterFiller/geometry/setXLength 38.39 mm
/gate/FM_AirGapAfterFiller/geometry/setYLength 19.145 mm
/gate/FM_AirGapAfterFiller/geometry/setZLength 0.0799 mm
/gate/FM_AirGapAfterFiller/placement/setTranslation 0 -9.5725 0.185 mm
/gate/FM_AirGapAfterFiller/setMaterial Air
/gate/FM_AirGapAfterFiller/vis/setVisible false

/gate/FM_Layer/daughters/name FM_AbsorberAirGap
/gate/FM_Layer/daughters/insert box
/gate/FM_AbsorberAirGap/geometry/setXLength 50.0 mm
/gate/FM_AbsorberAirGap/geometry/setYLength 50.0 mm
/gate/FM_AbsorberAirGap/geometry/setZLength 0.0749 mm
/gate/FM_AbsorberAirGap/placement/setTranslation 0 0 0.45 mm
/gate/FM_AbsorberAirGap/setMaterial Air
/gate/FM_AbsorberAirGap/vis/setVisible false
