/gate/world/geometry/setXLength 3500.0 mm
/gate/world/geometry/setYLength 3500.0 mm
/gate/world/geometry/setZLength 3500.0 mm
/gate/world/placement/setTranslation 0 0 0 mm
/gate/world/vis/setVisible false

/gate/world/daughters/name phantom
/gate/world/daughters/systemType scanner
/gate/world/daughters/insert box
/gate/phantom/geometry/setXLength 1650.0 mm
/gate/phantom/geometry/setYLength 1650.0 mm
/gate/phantom/geometry/setZLength {degraderthickness} mm
/gate/phantom/placement/setTranslation 0 0 {halfdegraderthickness} mm
/gate/phantom/vis/setVisible false

/gate/phantom/daughters/name degrader
/gate/phantom/daughters/insert box
/gate/degrader/geometry/setXLength 1500.0 mm
/gate/degrader/geometry/setYLength 1500.0 mm
/gate/degrader/geometry/setZLength {degraderthickness} mm
/gate/degrader/placement/setTranslation 0 0 0 mm
/gate/degrader/setMaterial Water
/gate/degrader/vis/setVisible false

/gate/world/daughters/name scanner_1
/gate/world/daughters/systemType scanner
/gate/world/daughters/insert box
/gate/scanner_1/geometry/setXLength 270.0 mm
/gate/scanner_1/geometry/setYLength 135.0 mm

/gate/scanner_1/geometry/setZLength 3.435 mm
/gate/scanner_1/placement/setTranslation 0 0 1.7175 mm
/gate/scanner_1/vis/setVisible false

/gate/world/daughters/name scanner_2
/gate/world/daughters/systemType scanner
/gate/world/daughters/insert box
/gate/scanner_2/geometry/setXLength 270.0 mm
/gate/scanner_2/geometry/setYLength 135.0 mm
/gate/scanner_2/geometry/setZLength 1030.5 mm
/gate/scanner_2/placement/setTranslation 0 0 518.685 mm
/gate/scanner_2/vis/setVisible false

/gate/scanner_1/daughters/name FM_Layer
/gate/scanner_1/daughters/insert box
/gate/FM_Layer/geometry/setXLength 270.0 mm
/gate/FM_Layer/geometry/setYLength 135.0 mm
/gate/FM_Layer/geometry/setZLength 3.435 mm
/gate/FM_Layer/placement/setTranslation 0 0 0 mm
/gate/FM_Layer/vis/setVisible false

/gate/FM_Layer/daughters/name FirstModule
/gate/FM_Layer/daughters/insert box
/gate/FirstModule/geometry/setXLength 270.0 mm
/gate/FirstModule/geometry/setYLength 135.0 mm
/gate/FirstModule/geometry/setZLength 0.35995 mm
/gate/FirstModule/placement/setTranslation 0 0 -1.5375 mm
/gate/FirstModule/vis/setVisible false

/gate/FirstModule/daughters/name FM_ActiveChip
/gate/FirstModule/daughters/insert box
/gate/FM_ActiveChip/geometry/setXLength 270.0 mm
/gate/FM_ActiveChip/geometry/setYLength 135.0 mm
/gate/FM_ActiveChip/geometry/setZLength 0.0139 mm
/gate/FM_ActiveChip/placement/setTranslation 0 0 -0.173 mm
/gate/FM_ActiveChip/setMaterial Silicon
/gate/FM_ActiveChip/vis/setColor red

/gate/FirstModule/daughters/name FM_PassiveChip
/gate/FirstModule/daughters/insert box
/gate/FM_PassiveChip/geometry/setXLength 270.0 mm
/gate/FM_PassiveChip/geometry/setYLength 135.0 mm
/gate/FM_PassiveChip/geometry/setZLength 0.1059 mm
/gate/FM_PassiveChip/placement/setTranslation 0 0 -0.113 mm
/gate/FM_PassiveChip/setMaterial Silicon
/gate/FM_PassiveChip/vis/setColor blue

/gate/FirstModule/daughters/name FM_ChipGlue
/gate/FirstModule/daughters/insert box
/gate/FM_ChipGlue/geometry/setXLength 270.0 mm
/gate/FM_ChipGlue/geometry/setYLength 135.0 mm
/gate/FM_ChipGlue/geometry/setZLength 0.0399 mm
/gate/FM_ChipGlue/placement/setTranslation 0 0 -0.04 mm
/gate/FM_ChipGlue/setMaterial Glue
/gate/FM_ChipGlue/vis/setColor yellow

/gate/FirstModule/daughters/name FM_PCB
/gate/FirstModule/daughters/insert box
/gate/FM_PCB/geometry/setXLength 270.0 mm
/gate/FM_PCB/geometry/setYLength 135.0 mm
/gate/FM_PCB/geometry/setZLength 0.1599 mm
/gate/FM_PCB/placement/setTranslation 0 0 0.06 mm
/gate/FM_PCB/setMaterial PCB
/gate/FM_PCB/vis/setColor green

/gate/FirstModule/daughters/name FM_PCBGlue
/gate/FirstModule/daughters/insert box
/gate/FM_PCBGlue/geometry/setXLength 270.0 mm
/gate/FM_PCBGlue/geometry/setYLength 135.0 mm
/gate/FM_PCBGlue/geometry/setZLength 0.0399 mm
/gate/FM_PCBGlue/placement/setTranslation 0 0 0.16 mm
/gate/FM_PCBGlue/setMaterial Glue
/gate/FM_PCBGlue/vis/setColor yellow

/gate/FM_Layer/daughters/name FM_Absorber1
/gate/FM_Layer/daughters/insert box
/gate/FM_Absorber1/geometry/setXLength 270.0 mm
/gate/FM_Absorber1/geometry/setYLength 135.0 mm
/gate/FM_Absorber1/geometry/setZLength 2.9999 mm
/gate/FM_Absorber1/placement/setTranslation 0 0 0.1425 mm
/gate/FM_Absorber1/setMaterial Air
/gate/FM_Absorber1/vis/setColor grey

/gate/FM_Layer/daughters/name FM_AbsorberAirGap
/gate/FM_Layer/daughters/insert box
/gate/FM_AbsorberAirGap/geometry/setXLength 270.0 mm
/gate/FM_AbsorberAirGap/geometry/setYLength 135.0 mm
/gate/FM_AbsorberAirGap/geometry/setZLength 0.0749 mm
/gate/FM_AbsorberAirGap/placement/setTranslation 0 0 1.68 mm
/gate/FM_AbsorberAirGap/setMaterial Air
/gate/FM_AbsorberAirGap/vis/setVisible false

/gate/scanner_2/daughters/name Layer
/gate/scanner_2/daughters/insert box
/gate/Layer/geometry/setXLength 270.0 mm
/gate/Layer/geometry/setYLength 135.0 mm
/gate/Layer/geometry/setZLength 3.435 mm
/gate/Layer/placement/setTranslation 0 0 -513.5325 mm
/gate/Layer/vis/setVisible false

/gate/Layer/daughters/name Module
/gate/Layer/daughters/insert box
/gate/Module/geometry/setXLength 270.0 mm
/gate/Module/geometry/setYLength 135.0 mm
/gate/Module/geometry/setZLength 0.35995 mm
/gate/Module/placement/setTranslation 0 0 -1.5375 mm
/gate/Module/vis/setVisible false

/gate/Module/daughters/name ActiveChip
/gate/Module/daughters/insert box
/gate/ActiveChip/geometry/setXLength 270.0 mm
/gate/ActiveChip/geometry/setYLength 135.0 mm
/gate/ActiveChip/geometry/setZLength 0.0139 mm
/gate/ActiveChip/placement/setTranslation 0 0 -0.173 mm
/gate/ActiveChip/setMaterial Silicon
/gate/ActiveChip/vis/setColor red

/gate/Module/daughters/name PassiveChip
/gate/Module/daughters/insert box
/gate/PassiveChip/geometry/setXLength 270.0 mm
/gate/PassiveChip/geometry/setYLength 135.0 mm
/gate/PassiveChip/geometry/setZLength 0.1059 mm
/gate/PassiveChip/placement/setTranslation 0 0 -0.113 mm
/gate/PassiveChip/setMaterial Silicon
/gate/PassiveChip/vis/setColor blue

/gate/Module/daughters/name ChipGlue
/gate/Module/daughters/insert box
/gate/ChipGlue/geometry/setXLength 270.0 mm
/gate/ChipGlue/geometry/setYLength 135.0 mm
/gate/ChipGlue/geometry/setZLength 0.0399 mm
/gate/ChipGlue/placement/setTranslation 0 0 -0.04 mm
/gate/ChipGlue/setMaterial Glue
/gate/ChipGlue/vis/setColor yellow

/gate/Module/daughters/name PCB
/gate/Module/daughters/insert box
/gate/PCB/geometry/setXLength 270.0 mm
/gate/PCB/geometry/setYLength 135.0 mm
/gate/PCB/geometry/setZLength 0.1599 mm
/gate/PCB/placement/setTranslation 0 0 0.06 mm
/gate/PCB/setMaterial PCB
/gate/PCB/vis/setColor green

/gate/Module/daughters/name PCBGlue
/gate/Module/daughters/insert box
/gate/PCBGlue/geometry/setXLength 270.0 mm
/gate/PCBGlue/geometry/setYLength 135.0 mm
/gate/PCBGlue/geometry/setZLength 0.0399 mm
/gate/PCBGlue/placement/setTranslation 0 0 0.16 mm
/gate/PCBGlue/setMaterial Glue
/gate/PCBGlue/vis/setColor yellow

/gate/Layer/daughters/name Absorber1
/gate/Layer/daughters/insert box
/gate/Absorber1/geometry/setXLength 270.0 mm
/gate/Absorber1/geometry/setYLength 135.0 mm
/gate/Absorber1/geometry/setZLength 2.9999 mm
/gate/Absorber1/placement/setTranslation 0 0 0.1425 mm
/gate/Absorber1/setMaterial Aluminium
/gate/Absorber1/vis/setColor grey

/gate/Layer/daughters/name AbsorberAirGap
/gate/Layer/daughters/insert box
/gate/AbsorberAirGap/geometry/setXLength 270.0 mm
/gate/AbsorberAirGap/geometry/setYLength 135.0 mm
/gate/AbsorberAirGap/geometry/setZLength 0.0749 mm
/gate/AbsorberAirGap/placement/setTranslation 0 0 1.68 mm
/gate/AbsorberAirGap/setMaterial Air
/gate/AbsorberAirGap/vis/setVisible false

/gate/Layer/repeaters/insert linear
/gate/Layer/linear/autoCenter false
/gate/Layer/linear/setRepeatNumber 150
/gate/Layer/linear/setRepeatVector 0 0 3.435 mm
