#/vis/open OGLSX
#/vis/viewer/reset
#/vis/viewer/set/viewpointThetaPhi 60 60
#/vis/viewer/zoom 10
#/vis/viewer/set/style surface
#/vis/drawVolume
#/tracking/storeTrajectory 1
#/vis/scene/endOfEventAction accumulate
#/vis/viewer/update

/gate/geometry/setMaterialDatabase GateMaterials.db

/gate/world/geometry/setXLength 1000. cm
/gate/world/geometry/setYLength 1000. cm
/gate/world/geometry/setZLength 1000. cm

/gate/world/daughters/name scanner
/gate/world/daughters/insert box
/gate/scanner/geometry/setXLength 100. cm
/gate/scanner/geometry/setYLength 100. cm
/gate/scanner/geometry/setZLength 100. cm
/gate/scanner/placement/setTranslation 0 0 50. cm
/gate/scanner/vis/forceWireframe

/gate/scanner/daughters/name phantom
/gate/scanner/daughters/insert box
/gate/phantom/geometry/setXLength 100. cm
/gate/phantom/geometry/setYLength 100. cm
/gate/phantom/geometry/setZLength 100. cm
/gate/phantom/placement/setTranslation 0 0 0 mm
/gate/phantom/setMaterial Water
/gate/phantom/vis/forceWireframe

/gate/phantom/attachCrystalSD

/gate/physics/addPhysicsList QGSP_BIC_EMZ
#/gate/physics/addPhysicsList QGSP_BIC_HP

/gate/geometry/setIonisationPotential Water 75 eV

#/gate/physics/addProcess HadronElastic
#/gate/physics/processes/HadronElastic/setModel G4HadronElastic
#/gate/physics/processes/HadronElastic/setDataSet G4HadronElasticDataSet

/gate/run/initialize

#/process/inactivate hadElastic
#/process/inactivate msc

#/gate/source/addSource PBS PencilBeam
#/gate/source/PBS/setParticleType proton
#/gate/source/PBS/setEnergy 250. MeV
#/gate/source/PBS/setSigmaEnergy 0. MeV
#/gate/source/PBS/setPosition 0 0 -10. mm
#/gate/source/PBS/setSigmaX 4 mm
#/gate/source/PBS/setSigmaY 2 mm
#/gate/source/PBS/setSigmaTheta 3.3 mrad
#/gate/source/PBS/setSigmaPhi 3.8 mrad
#/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
#/gate/source/PBS/setEllipseXThetaRotationNorm negative
#/gate/source/PBS/setEllipseYPhiEmittance 20 mm*mrad
#/gate/source/PBS/setEllipseYPhiRotationNorm negative

/gate/source/addSource PBS PencilBeam
/gate/source/PBS/setParticleType GenericIon
/gate/source/PBS/setIonProperties 2 4 2 0
#/gate/source/PBS/setIonProperties 6 12 6 0
/gate/source/PBS/setEnergy 917 MeV
/gate/source/PBS/setSigmaEnergy 0. MeV
/gate/source/PBS/setPosition 0. 0. -10 mm
/gate/source/PBS/setSigmaX 3 mm
/gate/source/PBS/setSigmaY 3 mm
/gate/source/PBS/setSigmaTheta 2 mrad
/gate/source/PBS/setSigmaPhi 2 mrad
/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance 15 mm*mrad
/gate/source/PBS/setEllipseYPhiRotationNorm negative
/gate/application/setTotalNumberOfPrimaries 1000

/gate/output/root/enable
/gate/output/root/setFileName output/waterphantom_HE

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/start
